services:
  untis-ics:
    image: ghcr.io/maxtheturtle0/mbg-untis-ical:latest
    container_name: untis-ics
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    # Uncomment if your Pi needs an explicit platform (e.g., 64-bit OS on Pi 4)
    # platform: linux/arm64
